# Schema for the configuration files of the om_cookies_styles module.
om_cookies_styles.settings:
  type: config_object
  label: 'om_cookies_styles settings'
  mapping:
    example:
      type: string
      label: 'Example'
